jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Application in Background
        run: nohup gunicorn -w 4 -b 0.0.0.0:5000 app:app &

      - name: Health Check
        run: |
          sleep 10
          curl -f http://127.0.0.1:5000 || exit 1

      - name: Terminate Flask Process
        run: pkill -f gunicorn
